# Generated by Django 5.1.1 on 2024-09-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_services_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='prompt',
            field=models.TextField(null=True),
        ),
    ]
