# Generated by Django 5.1.1 on 2024-09-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
    ]
