# Generated by Django 5.1.1 on 2024-10-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='color',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
