# Generated by Django 5.1.1 on 2024-10-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_newssite'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('text', models.CharField(max_length=1000)),
                ('pic', models.CharField(max_length=1000)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
