# Generated by Django 5.1.1 on 2024-10-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_newsreport_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsreport',
            name='pic',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='newsreport',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newsreport',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='newsreport',
            name='title',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
