# Generated by Django 5.1.2 on 2024-10-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_newsreport_pic_alter_newsreport_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=100)),
                ('prompt', models.TextField(null=True)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
