# Generated by Django 5.1.2 on 2024-10-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_service_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
