# Generated by Django 5.1.2 on 2024-10-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_socialintrest_telegram_socialintrest_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsreport',
            name='resource',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newssite',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
