# Generated by Django 5.1.2 on 2024-10-28 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_format_tone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsservice',
            name='slug',
        ),
    ]
