# Generated by Django 5.1.2 on 2024-10-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_staticentry_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='static_variables',
            field=models.JSONField(null=True),
        ),
    ]
