# Generated by Django 5.1.2 on 2024-10-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_service_static_variables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='static_variables',
        ),
        migrations.AddField(
            model_name='service',
            name='static_variables',
            field=models.ManyToManyField(to='main.staticentry'),
        ),
    ]
