# Generated by Django 5.1.2 on 2024-10-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_service_static_variables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='button_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
