# Generated by Django 5.1.2 on 2024-10-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_service_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_image',
            field=models.ImageField(null=True, upload_to='icons'),
        ),
    ]
