# Generated by Django 5.1.2 on 2024-10-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_ideastaticentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='variables',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
