# Generated by Django 5.1.2 on 2024-10-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_category_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='highlight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
