# Generated by Django 5.1.2 on 2024-11-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsreport',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
