# Generated by Django 5.1.2 on 2024-11-18 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_category_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
    ]
