# Generated by Django 5.1.2 on 2024-11-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_newsservice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
