# Generated by Django 5.1.2 on 2024-11-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_remove_service_highlight_remove_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsservice',
            name='icon_image',
            field=models.ImageField(null=True, upload_to='icons'),
        ),
    ]
