# Generated by Django 5.1.2 on 2024-11-24 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_newsresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsservice',
            name='price',
        ),
    ]
