# Generated by Django 5.1.2 on 2024-12-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_newsresult_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='json',
            field=models.JSONField(null=True),
        ),
    ]
