# Generated by Django 5.1.2 on 2024-12-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_newscategory_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscategory',
            name='json',
        ),
        migrations.AddField(
            model_name='newsservice',
            name='json',
            field=models.JSONField(null=True),
        ),
    ]
