# Generated by Django 5.1.2 on 2024-12-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_formatservice_rebuildservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssite',
            name='image',
            field=models.ImageField(null=True, upload_to='icons'),
        ),
    ]
