# Generated by Django 5.1.2 on 2024-12-13 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_newssite_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prompt', models.TextField(null=True)),
                ('description', models.CharField(max_length=1000)),
                ('json', models.JSONField(null=True)),
                ('icon_image', models.ImageField(null=True, upload_to='icons')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subservices', to='main.newscategory')),
            ],
        ),
    ]
