# Generated by Django 5.1.2 on 2024-12-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_remove_newssubservice_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsservice',
            name='category',
        ),
    ]
