# Generated by Django 5.1.2 on 2024-12-13 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_remove_newsservice_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsservice',
            name='json',
        ),
        migrations.RemoveField(
            model_name='newssubservice',
            name='json',
        ),
        migrations.AddField(
            model_name='newsservice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.newscategory'),
        ),
        migrations.AddField(
            model_name='newssite',
            name='json',
            field=models.JSONField(null=True),
        ),
    ]
