# Generated by Django 5.1.2 on 2024-12-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_remove_newsservice_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssite',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='static_variables',
            field=models.ManyToManyField(blank=True, null=True, to='main.staticentry'),
        ),
    ]
