# Generated by Django 5.1.2 on 2024-12-18 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_alter_newssite_json_alter_service_static_variables'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.newsservice')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.newssite')),
            ],
        ),
    ]
