# Generated by Django 5.1.2 on 2024-12-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_newslink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslink',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
