# Generated by Django 5.1.2 on 2024-12-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_remove_newssite_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssite',
            name='json',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
