# Generated by Django 5.1.2 on 2024-12-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_alter_newssite_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formatservice',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='rebuildservice',
            name='slug',
        ),
    ]
